require('dotenv').config();
const express = require('express');
const crypto = require('crypto');
const { Octokit } = require('octokit');
const axios = require('axios');
const winston = require('winston');

const logger = winston.createLogger({
  level: 'info',
  format: winston.format.json(),
  transports: [new winston.transports.Console()]
});

const app = express();
app.use(express.json({ limit: '10mb' }));

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

function verifyWebhookSignature(req) {
  const signature = req.headers['x-hub-signature-256'];
  if (!signature || !process.env.GITHUB_WEBHOOK_SECRET) return false;
  const hash = crypto
    .createHmac('sha256', process.env.GITHUB_WEBHOOK_SECRET)
    .update(JSON.stringify(req.body))
    .digest('hex');
  return signature === `sha256=${hash}`;
}

// Heuristic-based fallback review used while MIMO_API_KEY isn't configured.
// Same /api/review surface so the live demo works end-to-end before approval.
function localFallbackReview(code, language) {
  const issues = [];
  const good = [];
  const lc = code.toLowerCase();

  // Security smells
  if (/(['"])\s*\+\s*\w+|`[^`]*\$\{[^}]*\}[^`]*(select|insert|update|delete)/i.test(code) ||
      /(select|insert|update|delete)[^;]*['"]\s*\+/i.test(code)) {
    issues.push('🔴 **Security · SQL injection risk** — string-concatenated SQL detected. Use parameterized queries (`db.query("... WHERE id = ?", [id])`) instead of concatenating user input.');
  }
  if (/innerHTML\s*=/.test(code) && !/DOMPurify|sanitize/i.test(code)) {
    issues.push('🔴 **Security · XSS** — direct `innerHTML` assignment without sanitization. Use `textContent` or sanitize with DOMPurify.');
  }
  if (/(api[_-]?key|password|secret|token)\s*[:=]\s*["'][a-z0-9_\-]{12,}/i.test(code)) {
    issues.push('🔴 **Security · hardcoded credential** — secrets should live in environment variables, not source.');
  }
  if (/eval\s*\(/.test(code) || /new\s+Function\s*\(/.test(code)) {
    issues.push('🔴 **Security · arbitrary code execution** — `eval`/`new Function` enables RCE if input is untrusted.');
  }

  // Bugs / correctness
  if (/console\.log\s*\(\s*err/i.test(code) && !/throw|reject|return/.test(code.split(/console\.log/)[1] || '')) {
    issues.push('🟡 **Bug · swallowed error** — error is logged but not propagated. Caller will see `undefined` instead of failing fast.');
  }
  if (/db\.query\([^)]*,\s*\([^)]*\)\s*=>/.test(code) && /return\s+rows/.test(code)) {
    issues.push('🟡 **Bug · async return** — returning from inside a callback does not return from the outer function. Wrap in a Promise or use the promisified driver / `async/await`.');
  }
  if (/==\s*null|!=\s*null/.test(code)) {
    issues.push('🟡 **Quality · loose equality** — prefer `=== null` / `!== null` to avoid `undefined` coercion surprises (unless that coercion is intentional).');
  }
  if (/\bvar\s+/.test(code) && language.match(/javascript|typescript/i)) {
    issues.push('🟡 **Quality · `var`** — prefer `const`/`let` for block scoping.');
  }
  if (language.match(/python/i) && /except\s*:\s*$/m.test(code)) {
    issues.push('🟡 **Bug · bare except** — catches `KeyboardInterrupt`/`SystemExit`. Use `except Exception:`.');
  }

  // Perf
  if (/for\s*\([^)]+\)\s*\{[^}]*\.length/.test(code)) {
    issues.push('🟢 **Perf · cache `.length`** — accessing `arr.length` per iteration is fine for arrays, but matters for live `NodeList`/strings.');
  }
  if (/await[^;]+;\s*await/.test(code)) {
    issues.push('🟢 **Perf · serial awaits** — independent awaits can run in parallel via `Promise.all([...])`.');
  }

  // Positives (so review feels balanced)
  if (/try\s*\{[\s\S]*?\}\s*catch/.test(code)) good.push('Try/catch error handling present.');
  if (/(const|let)\s+\w+\s*=/.test(code)) good.push('Block-scoped declarations used.');
  if (/\/\/|\/\*|"""|#\s/.test(code)) good.push('Code is commented.');
  if (code.split('\n').length < 30) good.push('Function is small and focused.');

  // Compose
  const lines = [];
  lines.push(`### Review summary (${language})`);
  lines.push('');
  if (good.length) {
    lines.push('**✅ Looks good**');
    good.forEach(g => lines.push(`- ${g}`));
    lines.push('');
  }
  if (issues.length) {
    lines.push('**⚠️ Findings**');
    issues.forEach(i => lines.push(`- ${i}`));
    lines.push('');
  } else {
    lines.push('No critical issues spotted by the static pass.');
    lines.push('');
  }
  lines.push('_Note: this response was generated by the local heuristic pass while MiMo API key is being provisioned. Once `MIMO_API_KEY` is set, the same endpoint serves real Xiaomi MiMo V2.5 output._');
  return lines.join('\n');
}

async function reviewCodeWithMIMO(code, language = 'javascript') {
  // No key → use local heuristic so the live demo stays working
  if (!process.env.MIMO_API_KEY) {
    return { text: localFallbackReview(code, language), source: 'local-heuristic' };
  }
  const response = await axios.post(
    `${process.env.MIMO_API_URL || 'https://api.xiaomimimo.com'}/v1/chat/completions`,
    {
      model: 'mimo-v2.5',
      messages: [
        {
          role: 'system',
          content: `You are an expert code reviewer. Analyze ${language} code for bugs, performance, security, and best practices. Return a concise structured review with sections: Looks good, Findings (severity-tagged), and Suggested fix snippets when applicable.`
        },
        { role: 'user', content: `Review this ${language} code:\n\n${code}` }
      ],
      temperature: 0.5,
      max_tokens: 1000
    },
    {
      headers: {
        Authorization: `Bearer ${process.env.MIMO_API_KEY}`,
        'Content-Type': 'application/json'
      },
      timeout: 25000
    }
  );
  return { text: response.data.choices[0].message.content, source: 'mimo-v2.5' };
}

async function postReviewComment(owner, repo, prNumber, review) {
  const comment = `🤖 **AI Code Review by MiMo**\n\n${review}\n\n---\n⏱️ ${new Date().toISOString()}`;
  await octokit.rest.issues.createComment({
    owner, repo, issue_number: prNumber, body: comment
  });
}

app.post('/api/webhook', async (req, res) => {
  if (!verifyWebhookSignature(req)) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  const event = req.headers['x-github-event'];
  if (event !== 'pull_request') return res.status(200).json({ message: 'ignored' });

  const { action, pull_request, repository } = req.body;
  if (!['opened', 'synchronize'].includes(action)) {
    return res.status(200).json({ message: 'action ignored' });
  }

  // Vercel functions have ~10s default timeout on hobby; respond fast then process async
  res.status(202).json({ message: 'review queued' });

  try {
    const owner = repository.owner.login;
    const repo = repository.name;
    const prNumber = pull_request.number;
    const { data: files } = await octokit.rest.pulls.listFiles({
      owner, repo, pull_number: prNumber
    });
    const reviews = [];
    for (const file of files.slice(0, 3)) {
      if (file.patch && file.patch.length < 4000) {
        try {
          const r = await reviewCodeWithMIMO(file.patch, file.filename.split('.').pop());
          reviews.push(`**${file.filename}**\n${r.text}`);
        } catch (e) {
          logger.error(`review failed for ${file.filename}: ${e.message}`);
        }
      }
    }
    if (reviews.length) {
      await postReviewComment(owner, repo, prNumber, reviews.join('\n\n---\n\n'));
    }
  } catch (e) {
    logger.error(`webhook processing: ${e.message}`);
  }
});

app.post('/api/review', async (req, res) => {
  try {
    const { code, language = 'javascript' } = req.body;
    if (!code) return res.status(400).json({ error: 'code required' });
    const r = await reviewCodeWithMIMO(code, language);
    res.json({
      review: r.text,
      source: r.source,
      tokens_used: Math.floor(code.length / 4)
    });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.get('/api/health', (req, res) => {
  res.json({
    status: 'ok',
    service: 'ai-code-reviewer',
    timestamp: new Date().toISOString(),
    runtime: 'vercel-serverless'
  });
});

// Local dev fallback
if (process.env.NODE_ENV !== 'production' && require.main === module) {
  const PORT = process.env.PORT || 3000;
  app.listen(PORT, () => logger.info(`🚀 local dev on :${PORT}`));
}

module.exports = app;
